#!/usr/bin/env bash
#
# Create one pull request per creator's collected YouTube transcripts.
#
# For every creator that has files under research/youtube-transcripts/<slug>/,
# this script creates an isolated branch off the base branch, commits *only*
# that creator's transcript folder (plus its index.md), pushes it, and opens a
# PR. One creator == one branch == one PR.
#
# Prerequisites (run locally, not in the egress-restricted web env):
#   - You have already run collect.py so transcripts exist on disk.
#   - `git` and the GitHub CLI `gh` are installed and authenticated.
#
# Usage:
#   research/other/make_creator_prs.sh                 # all creators with transcripts
#   research/other/make_creator_prs.sh josh-braun      # just one creator
#   BASE=main research/other/make_creator_prs.sh       # override base branch (default: main)
#
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

BASE="${BASE:-main}"
CREATORS_JSON="research/other/creators.json"
YT_ROOT="research/youtube-transcripts"

command -v gh >/dev/null 2>&1 || { echo "ERROR: gh (GitHub CLI) not found." >&2; exit 1; }

# Build the slug->name map once, from creators.json.
read_name() {
  python3 - "$1" <<'PY'
import json, sys
slug = sys.argv[1]
data = json.load(open("research/other/creators.json"))
for c in data["creators"]:
    if c["slug"] == slug:
        print(c["name"]); break
else:
    print(slug)
PY
}

# Determine which slugs to process.
if [[ $# -gt 0 ]]; then
  SLUGS=("$@")
else
  mapfile -t SLUGS < <(python3 -c "import json;print('\n'.join(c['slug'] for c in json.load(open('$CREATORS_JSON'))['creators']))")
fi

made=0
for slug in "${SLUGS[@]}"; do
  dir="$YT_ROOT/$slug"
  # Count real transcript files (ignore the generated index.md).
  shopt -s nullglob
  files=("$dir"/*.md)
  files=("${files[@]/$dir\/index.md}")
  count=0; for f in "${files[@]}"; do [[ -n "$f" && "$(basename "$f")" != "index.md" ]] && ((count++)); done
  shopt -u nullglob

  if [[ "$count" -eq 0 ]]; then
    echo "skip $slug — no transcripts in $dir"
    continue
  fi

  name="$(read_name "$slug")"
  branch="claude/transcripts-$slug"
  echo "=== $name ($slug): $count transcript(s) -> $branch ==="

  git fetch origin "$BASE" --quiet || true
  git switch -C "$branch" "origin/$BASE" 2>/dev/null || git switch -C "$branch" "$BASE"

  # Stage only this creator's transcript folder.
  git add -- "$dir"
  if git diff --cached --quiet; then
    echo "  nothing new to commit for $slug; skipping"
    git switch - >/dev/null 2>&1 || true
    continue
  fi

  git commit -q -m "Collect YouTube transcripts: $name

$count transcript(s) collected via the Supadata API into $dir/."

  # Push with simple exponential backoff on transient network failures.
  delay=2
  for attempt in 1 2 3 4 5; do
    if git push -u origin "$branch"; then break; fi
    echo "  push failed (attempt $attempt); retrying in ${delay}s..."; sleep "$delay"; delay=$((delay*2))
  done

  gh pr create \
    --base "$BASE" \
    --head "$branch" \
    --title "Collect YouTube transcripts: $name" \
    --body "$(printf '## Summary\n\n%d YouTube transcript(s) for **%s**, collected via the Supadata API.\n\nFiles live in `%s/`, with a navigable `index.md` table of contents.\n\n_One creator per PR (generated by `research/other/make_creator_prs.sh`)._' "$count" "$name" "$dir")"

  ((made++)) || true
  git switch "$BASE" >/dev/null 2>&1 || true
done

echo "Done. Created/updated $made creator PR(s)."
