#!/usr/bin/env python3
"""Generate navigable index.md tables of contents for collected content.

Scans the directories that collect.py populates and writes:

  research/youtube-transcripts/<slug>/index.md   # per-creator TOC of videos
  research/linkedin-posts/<slug>/index.md        # per-creator TOC of posts
  research/index.md                              # master TOC across all creators

Each index links to every collected file with its title, source URL, date, and a
short snippet. Safe to run any time — it only indexes directories that actually
contain content, and rewrites indexes idempotently. Run it standalone or let
collect.py call it automatically after a collection run.

Usage:
  python3 research/other/make_index.py
"""
from __future__ import annotations

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # research/
CONTENT_TYPES = [
    ("youtube-transcripts", "YouTube transcripts", "Videos"),
    ("linkedin-posts", "LinkedIn posts", "Posts"),
]


def parse_meta(path: str) -> dict:
    """Extract title, bullet metadata, and a snippet from a collected .md file."""
    meta = {"title": os.path.basename(path), "source": "", "date": "", "snippet": ""}
    try:
        with open(path, encoding="utf-8") as f:
            lines = f.read().splitlines()
    except OSError:
        return meta

    body_started = False
    snippet_parts: list[str] = []
    for line in lines:
        if line.startswith("# ") and meta["title"] == os.path.basename(path):
            meta["title"] = line[2:].strip()
            continue
        m = re.match(r"^- \*?\*?(\w[\w ]*?)\*?\*?:\s*(.+)$", line)
        if m:
            key, val = m.group(1).strip().lower(), m.group(2).strip()
            if key == "source":
                meta["source"] = val
            elif key in ("posted", "published", "collected", "date") and not meta["date"]:
                meta["date"] = val
            continue
        if line.startswith("## "):  # e.g. "## Transcript" — body follows
            body_started = True
            continue
        text = line.strip()
        if text and not text.startswith(("#", "-")):
            body_started = True
        if body_started and text:
            snippet_parts.append(text)
            if sum(len(p) for p in snippet_parts) > 140:
                break

    snippet = " ".join(snippet_parts)
    snippet = re.sub(r"\s+", " ", snippet).strip()
    if len(snippet) > 140:
        snippet = snippet[:137].rstrip() + "…"
    meta["snippet"] = snippet
    return meta


def list_content_files(dir_path: str) -> list[str]:
    if not os.path.isdir(dir_path):
        return []
    return sorted(
        f for f in os.listdir(dir_path)
        if f.endswith(".md") and f != "index.md"
    )


def build_creator_index(content_type: str, label: str, slug: str, name: str) -> int:
    """Write a per-creator index.md; return the number of items indexed."""
    dir_path = os.path.join(ROOT, content_type, slug)
    files = list_content_files(dir_path)
    if not files:
        return 0

    entries = [(f, parse_meta(os.path.join(dir_path, f))) for f in files]
    # Newest first when dates are present; unknown/empty dates sink to the bottom.
    entries.sort(key=lambda e: (e[1]["date"] or "0000"), reverse=True)

    rows = ["| # | Title | Date | Source | Preview |", "|---|---|---|---|---|"]
    for i, (fname, m) in enumerate(entries, 1):
        title = m["title"].replace("|", "\\|")
        snippet = (m["snippet"] or "—").replace("|", "\\|")
        source = f"[link]({m['source']})" if m["source"] else "—"
        rows.append(f"| {i} | [{title}]({fname}) | {m['date'] or '—'} | {source} | {snippet} |")

    body = (
        f"# {name} — {label}\n\n"
        f"_{len(entries)} item(s). Auto-generated by `research/other/make_index.py` — do not edit by hand._\n\n"
        + "\n".join(rows) + "\n"
    )
    with open(os.path.join(dir_path, "index.md"), "w", encoding="utf-8") as f:
        f.write(body)
    return len(entries)


def build_master_index(creators: list[dict], counts: dict) -> None:
    """Write research/index.md linking every per-creator index that exists."""
    lines = [
        "# Research index",
        "",
        "Navigable table of contents for all collected creator content. "
        "Auto-generated by `research/other/make_index.py` — re-run it after each "
        "collection to refresh.",
        "",
        "| Creator | Rank | Score | YouTube transcripts | LinkedIn posts |",
        "|---|---|---|---|---|",
    ]
    for c in creators:
        slug, name = c["slug"], c["name"]
        yt = counts.get((slug, "youtube-transcripts"), 0)
        li = counts.get((slug, "linkedin-posts"), 0)
        yt_cell = f"[{yt} →](youtube-transcripts/{slug}/index.md)" if yt else "—"
        li_cell = f"[{li} →](linkedin-posts/{slug}/index.md)" if li else "—"
        lines.append(
            f"| {name} | {c.get('rank', '—')} | {c.get('score', '—')} | {yt_cell} | {li_cell} |"
        )

    total_yt = sum(v for (s, t), v in counts.items() if t == "youtube-transcripts")
    total_li = sum(v for (s, t), v in counts.items() if t == "linkedin-posts")
    lines += [
        "",
        f"**Totals:** {total_yt} YouTube transcript(s), {total_li} LinkedIn post(s) "
        f"across {len(creators)} creators.",
        "",
        "See [`sources.md`](sources.md) for the full benchmark catalog and scoring rubric.",
        "",
    ]
    with open(os.path.join(ROOT, "index.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def build_all() -> dict:
    """Build every index. Returns {(slug, content_type): count}."""
    with open(os.path.join(os.path.dirname(__file__), "creators.json"), encoding="utf-8") as f:
        creators = json.load(f)["creators"]

    counts: dict = {}
    for c in creators:
        for content_type, label, _ in CONTENT_TYPES:
            counts[(c["slug"], content_type)] = build_creator_index(
                content_type, label, c["slug"], c["name"]
            )
    build_master_index(creators, counts)
    return counts


def main() -> int:
    counts = build_all()
    indexed = sum(1 for v in counts.values() if v)
    total = sum(counts.values())
    print(f"Generated master index + {indexed} per-creator index(es); {total} item(s) total.")
    if total == 0:
        print("No collected content yet — indexes will fill in once collect.py runs.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
